### ISSUE TITLE
multiple toasts

### ISSUE THREAD

**Issue by jamesj2** [php-flasher/flasher-sweet-alert-laravel#3]
Is it possible to have more than 1 sweet alert toast on a page?  I was able to accomplish this with [flasher-toastr-laravel](https://github.com/php-flasher/flasher-toastr-laravel) using the toastr() helper.  After changing over to sweet alerts I'm only able to show one toast at a time using the sweetAlert() helper.  I have verified multiple envelopes show up in the blade output.

**Comment by yoeunes-spin** [comment]
Hello @jamesj2 this is an issue with sweet alert js library :  https://github.com/sweetalert2/sweetalert2/issues/808

**Comment by jamesj2** [comment]
Thanks for that.  I will use something else.

**Comment by yoeunes** [comment]
Hello @jamesj2  can you please upgrade to v0.4.10,  and check if all your sweet alert notifications are displayed one after one ?
update also the cdn version or javascript related files : flasher-js and flasher-sweet-alert-js

**Comment by yoeunes** [comment]
https://github.com/php-flasher/flasher-laravel/blob/main/Resources/config/config.php#L7

https://github.com/php-flasher/flasher-sweet-alert-laravel/blob/main/Resources/config/config.php#L6

**Comment by jamesj2** [comment]
> Hello @jamesj2 can you please upgrade to v0.4.11, and check if all your sweet alert notifications are displayed one after one ?
> update also the cdn version or javascript related files : flasher-js and flasher-sweet-alert-js
> 
> [jamesj2/laravel-flasher-pnotify-js-issue#2](https://github.com/jamesj2/laravel-flasher-pnotify-js-issue/pull/2)

Awesome, after upgrading to composer packages version 0.4.11 and node packages to 0.1.6 it's working.   Thanks!
